export type FormationSlot = { x: number; y: number; label: string };

// x: 0 (sol) - 100 (sağ), y: 0 (kendi kalesi) - 100 (rakip kalesi)
// İlk pozisyon her zaman kaleci.
export const FORMATIONS: Record<string, FormationSlot[]> = {
  "4-4-2": [
    { x: 50, y: 5, label: "Kaleci" },
    { x: 15, y: 22, label: "Sol Bek" },
    { x: 38, y: 20, label: "Stoper" },
    { x: 62, y: 20, label: "Stoper" },
    { x: 85, y: 22, label: "Sağ Bek" },
    { x: 15, y: 50, label: "Sol Kanat" },
    { x: 38, y: 48, label: "Orta Saha" },
    { x: 62, y: 48, label: "Orta Saha" },
    { x: 85, y: 50, label: "Sağ Kanat" },
    { x: 38, y: 78, label: "Forvet" },
    { x: 62, y: 78, label: "Forvet" },
  ],
  "4-3-3": [
    { x: 50, y: 5, label: "Kaleci" },
    { x: 15, y: 22, label: "Sol Bek" },
    { x: 38, y: 20, label: "Stoper" },
    { x: 62, y: 20, label: "Stoper" },
    { x: 85, y: 22, label: "Sağ Bek" },
    { x: 25, y: 48, label: "Orta Saha" },
    { x: 50, y: 45, label: "Orta Saha" },
    { x: 75, y: 48, label: "Orta Saha" },
    { x: 20, y: 78, label: "Sol Kanat" },
    { x: 50, y: 82, label: "Forvet" },
    { x: 80, y: 78, label: "Sağ Kanat" },
  ],
  "4-2-3-1": [
    { x: 50, y: 5, label: "Kaleci" },
    { x: 15, y: 22, label: "Sol Bek" },
    { x: 38, y: 20, label: "Stoper" },
    { x: 62, y: 20, label: "Stoper" },
    { x: 85, y: 22, label: "Sağ Bek" },
    { x: 35, y: 40, label: "Ön Libero" },
    { x: 65, y: 40, label: "Ön Libero" },
    { x: 20, y: 62, label: "Sol Kanat" },
    { x: 50, y: 60, label: "Ofansif Orta Saha" },
    { x: 80, y: 62, label: "Sağ Kanat" },
    { x: 50, y: 85, label: "Forvet" },
  ],
  "3-5-2": [
    { x: 50, y: 5, label: "Kaleci" },
    { x: 25, y: 20, label: "Stoper" },
    { x: 50, y: 18, label: "Stoper" },
    { x: 75, y: 20, label: "Stoper" },
    { x: 10, y: 48, label: "Sol Kanat Bek" },
    { x: 32, y: 45, label: "Orta Saha" },
    { x: 50, y: 42, label: "Orta Saha" },
    { x: 68, y: 45, label: "Orta Saha" },
    { x: 90, y: 48, label: "Sağ Kanat Bek" },
    { x: 38, y: 78, label: "Forvet" },
    { x: 62, y: 78, label: "Forvet" },
  ],
  "3-4-3": [
    { x: 50, y: 5, label: "Kaleci" },
    { x: 25, y: 20, label: "Stoper" },
    { x: 50, y: 18, label: "Stoper" },
    { x: 75, y: 20, label: "Stoper" },
    { x: 15, y: 48, label: "Sol Kanat" },
    { x: 38, y: 45, label: "Orta Saha" },
    { x: 62, y: 45, label: "Orta Saha" },
    { x: 85, y: 48, label: "Sağ Kanat" },
    { x: 20, y: 78, label: "Sol Forvet" },
    { x: 50, y: 82, label: "Santrfor" },
    { x: 80, y: 78, label: "Sağ Forvet" },
  ],
  "5-3-2": [
    { x: 50, y: 5, label: "Kaleci" },
    { x: 10, y: 25, label: "Sol Kanat Bek" },
    { x: 30, y: 20, label: "Stoper" },
    { x: 50, y: 18, label: "Stoper" },
    { x: 70, y: 20, label: "Stoper" },
    { x: 90, y: 25, label: "Sağ Kanat Bek" },
    { x: 30, y: 50, label: "Orta Saha" },
    { x: 50, y: 46, label: "Orta Saha" },
    { x: 70, y: 50, label: "Orta Saha" },
    { x: 38, y: 78, label: "Forvet" },
    { x: 62, y: 78, label: "Forvet" },
  ],
  "5-4-1": [
    { x: 50, y: 5, label: "Kaleci" },
    { x: 10, y: 25, label: "Sol Kanat Bek" },
    { x: 30, y: 20, label: "Stoper" },
    { x: 50, y: 18, label: "Stoper" },
    { x: 70, y: 20, label: "Stoper" },
    { x: 90, y: 25, label: "Sağ Kanat Bek" },
    { x: 15, y: 50, label: "Sol Kanat" },
    { x: 38, y: 48, label: "Orta Saha" },
    { x: 62, y: 48, label: "Orta Saha" },
    { x: 85, y: 50, label: "Sağ Kanat" },
    { x: 50, y: 80, label: "Santrfor" },
  ],
};

export const FORMATION_NAMES = Object.keys(FORMATIONS);
export const DEFAULT_FORMATION = "4-4-2";
